### ISSUE TITLE
horizontal scrolling carousel with slick for projects section

### ISSUE THREAD

**Issue by eemshi** [mmmanyfold/www#31]
variable width, full width
![screen shot 2017-03-27 at 10 06 22 pm](https://cloud.githubusercontent.com/assets/10643091/24385753/d69daefc-1339-11e7-985f-55cf25d6e4d0.png)

**Comment by dviramontes** [comment]
for the initial render of the projects we use slick library and once you click on the project, project becomes full screen
look at variable width example 
http://kenwheeler.github.io/slick/
